### ISSUE TITLE
QUESTION: Can we control a function flow with pyintercept?

### ISSUE THREAD

**Issue by db-vmw** [caioariede/pyintercept#1]
Hello @caioariede ,
Thanks for contributing to a nice utility. 
Is this possible to intercept and control a function part of python program? 
Example:
Let's say there is function:
```
def funDef(args ..):
    try{
         ....
    } catch (exception ex){
        ...
    }
```

Is this possible to control the function "funDef" so that, every time, funDef is called, the program should return code in the exception block, irrespective of the condition in try block.

Thanks,
Dinesh

**Comment by caioariede** [comment]
@db-vmw I think for that you would need to write some specific code to extract the code inside the try-except block. Sorry for the long time, it's been a long time since I wrote this code
