### ISSUE TITLE
QUESTION: Intercept many functions in a single code

### ISSUE THREAD

**Issue by Nivekiba** [caioariede/pyintercept#2]
Hello @caioariede , i'm actually working in a project where it's necessary for me to intercept functions.

But i'm facing a  problem with your tool: 

It's possible to intercept many functions while executing a single python code ?

**Comment by caioariede** [comment]
It's been a long long time since I've worked on this, so I don't really remember all the details

Sorry about that

**Comment by Nivekiba** [comment]
Ok Ok
